from datetime import datetime

products = [
    {
        "name": "Product 1",
        "description": "Description for product 1",
        "price": 10.99,
        "image_url": "/1.jpg",
        "contact_details": "contact1@example.com",
        "tags": "1,2",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 2",
        "description": "Description for product 2",
        "price": 20.99,
        "image_url": "/2.jpg",
        "contact_details": "contact2@example.com",
        "tags": "2,3",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 3",
        "description": "Description for product 3",
        "price": 30.99,
        "image_url": "/3.jpg",
        "contact_details": "contact3@example.com",
        "tags": "1,3",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 4",
        "description": "Description for product 4",
        "price": 40.99,
        "image_url": "/4.jpg",
        "contact_details": "contact4@example.com",
        "tags": "1,4",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 5",
        "description": "Description for product 5",
        "price": 50.99,
        "image_url": "/5.jpg",
        "contact_details": "contact5@example.com",
        "tags": "2,4",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 6",
        "description": "Description for product 6",
        "price": 60.99,
        "image_url": "/6.jpg",
        "contact_details": "contact6@example.com",
        "tags": "3,4",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 7",
        "description": "Description for product 7",
        "price": 70.99,
        "image_url": "/7.jpg",
        "contact_details": "contact7@example.com",
        "tags": "1,2",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 8",
        "description": "Description for product 8",
        "price": 80.99,
        "image_url": "/8.jpg",
        "contact_details": "contact8@example.com",
        "tags": "2,3",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 9",
        "description": "Description for product 9",
        "price": 90.99,
        "image_url": "/9.jpg",
        "contact_details": "contact9@example.com",
        "tags": "1,3",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Product 10",
        "description": "Description for product 10",
        "price": 100.99,
        "image_url": "/10.jpg",
        "contact_details": "contact10@example.com",
        "tags": "1,4",
        "date_posted": datetime.utcnow(),
    },
]
