from datetime import datetime


products = [
    {
        "name": "Eco-friendly Water Bottle",
        "description": "Durable, BPA-free water bottle made from recycled materials. Ideal for outdoor activities and daily use. Features a leak-proof cap and a handy carrying strap. Capacity: 750ml.",
        "price": 10.99,
        "image_url": "/bottle.jpg",
        "contact_details": "contact1@example.com",
        "tags": "1, 2",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Wireless Bluetooth Headphones",
        "description": "High-fidelity sound with noise-cancellation technology. Comfortable over-ear design suitable for long listening sessions. Battery life up to 12 hours. Available in black and silver.",
        "price": 20.99,
        "image_url": "/wireless-bt-headphones.jpg",
        "contact_details": "contact2@example.com",
        "tags": "3, 4, 5",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Organic Hand Cream",
        "description": "Moisturizing hand cream made from organic shea butter and essential oils. Softens and protects dry skin. Free from parabens and synthetic fragrances. Volume: 50ml.",
        "price": 30.99,
        "image_url": "organic-hand-cream.jpg",
        "contact_details": "contact3@example.com",
        "tags": "6, 7",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Compact Camping Tent",
        "description": "Lightweight, waterproof camping tent for two people. Easy to set up with durable poles and stakes. Includes a storage bag for easy transport. Ideal for hiking and weekend trips.",
        "price": 40.99,
        "image_url": "tent.jpg",
        "contact_details": "contact4@example.com",
        "tags": "8, 9",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Gourmet Coffee Beans",
        "description": "Premium blend of Arabica and Robusta beans sourced from Colombia and Brazil. Offers a rich, bold flavor with notes of chocolate and caramel. Perfect for espresso and French press brewing. Weight: 500g.",
        "price": 50.99,
        "image_url": "coffee-beans.jpg",
        "contact_details": "contact5@example.com",
        "tags": "10, 11",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Smart Fitness Tracker",
        "description": "Advanced fitness tracker with heart rate monitor and GPS tracking. Syncs with iOS and Android. Tracks steps, calories, and sleep patterns. Waterproof up to 50 meters.",
        "price": 60.99,
        "image_url": "fitness-tracker.jpg",
        "contact_details": "contact6@example.com",
        "tags": "12, 13, 3",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Luxury Silk Scarf",
        "description": "Elegant silk scarf featuring a hand-painted floral design. Versatile accessory that can be worn in various styles. Material: 100% pure silk. Dimensions: 50cm x 180cm.",
        "price": 70.99,
        "image_url": "scarf.jpg",
        "contact_details": "contact7@example.com",
        "tags": "14, 15",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Professional Watercolor Set",
        "description": "Artist-grade watercolor paint set including 24 vibrant colors. High pigment load for impressive saturation. Comes with brushes and a mixing palette. Suitable for beginners and professionals.",
        "price": 80.99,
        "image_url": "watercolor.jpg",
        "contact_details": "contact8@example.com",
        "tags": "17, 18",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Leather Journal Notebook",
        "description": "Handcrafted notebook with genuine leather cover and refillable acid-free paper. Ideal for journaling, sketching, or personal notes. Size: A5. Includes a ribbon bookmark.",
        "price": 90.99,
        "image_url": "journal.jpg",
        "contact_details": "contact9@example.com",
        "tags": "19, 20",
        "date_posted": datetime.utcnow(),
    },
    {
        "name": "Advanced Drone with Camera",
        "description": "High-performance drone suitable for aerial photography and videography. Features 4K camera, stable hover, and easy-to-use controls. Flight time: up to 30 minutes. Includes carrying case.",
        "price": 100.99,
        "image_url": "drone.jpg",
        "contact_details": "contact10@example.com",
        "tags": "3, 21",
        "date_posted": datetime.utcnow(),
    },
]
