tags = [
    {"name": "Eco", "color_code": "#5cb85c"},
    {"name": "Outdoor", "color_code": "#5bc0de"},
    {"name": "Tech", "color_code": "#f0ad4e"},
    {"name": "Music", "color_code": "#d9534f"},
    {"name": "Gadgets", "color_code": "#5bc0de"},
    {"name": "Beauty", "color_code": "#5cb85c"},
    {"name": "Skincare", "color_code": "#f0ad4e"},
    {"name": "Camping", "color_code": "#d9534f"},
    {"name": "Travel", "color_code": "#5cb85c"},
    {"name": "Coffee", "color_code": "#5bc0de"},
    {"name": "Gourmet", "color_code": "#f0ad4e"},
    {"name": "Fitness", "color_code": "#d9534f"},
    {"name": "Health", "color_code": "#5cb85c"},
    {"name": "Fashion", "color_code": "#5bc0de"},
    {"name": "Luxury", "color_code": "#f0ad4e"},
    {"name": "Accessories", "color_code": "#d9534f"},
    {"name": "Art", "color_code": "#5cb85c"},
    {"name": "Crafts", "color_code": "#5bc0de"},
    {"name": "Stationery", "color_code": "#f0ad4e"},
    {"name": "Books", "color_code": "#d9534f"},
    {"name": "Photography", "color_code": "#5cb85c"},
]
